services:
  - type: web
    name: rw-fullstack
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STREAMING_SITE_URL
        sync: false
      - key: STREAMING_API_SECRET
        sync: false
      - key: PORT
        value: 3001
